apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpserver
  labels:
    app: httpserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpserver
  template:
    metadata:
      labels:
        app: httpserver
    spec:
      imagePullSecrets:
        - name: cloudnative
      containers:
        - name: httpserver
          image: totorest/httpserver:v1.8.1
          ports:
          - containerPort: 19004
          readinessProbe:
            httpGet:
              path: /healthz
              port: 19004
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 3
          resources:
            limits:
              memory: "200Mi"
              cpu: 200m
            requests:
              memory: "100Mi"
              cpu: 20m
          volumeMounts:
          - name: config
            mountPath: /
      volumes:
      - name: config  
        configMap:
          name: httpserver-config